on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Unit testing
        run: pytest test